vich_uploader:
    db_driver: orm

    mappings:
        song_image:
            uri_prefix: /upload/song
            upload_destination: '%kernel.project_dir%/public/upload/song'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
